version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_DB=mongodb://mongodb:27017/mydatabase
      - PORT=3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

  app-test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_DB=mongodb://mongodb-test:27017/mytestdatabase
      - PORT=3000
    command: [ "npm", "run", "test" ]
    depends_on:
      - mongodb-test

  mongodb-test:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongodb-test-data:/data/db

volumes:
  mongodb-data:
  mongodb-test-data:
